title: Doctrine Directory
url: https://doctrine.directory
sourceUrl: https://github.com/mminer237/doctrine-directory
author: Matthew Miner
# tagManagerCode: GTM-TK37G57
# googleAdClient: ca-pub-5576042369154755
lightThemeColor: "#e33636"
darkThemeColor: "#ce1c1c"
msTileColor: "#da532c"

googleFonts:
  - Vesper+Libre:wght@700&text=1234567890
  - Frank+Ruhl+Libre:wght@400;700&subset=hebrew

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "doctrines"
    values:
      layout: "page"

collections:
  pages:
    output: true
    permalink: /:name
  doctrines:
    output: true
    permalink: /:path

permalink: /:name

sass:
  style: compressed

kramdown:
  smart_quotes: ["apos", "apos", "ldquo", "rdquo"]

plugins:
  - jekyll-responsive-image
  - jekyll-sitemap

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 400
    - width: 765
  auto_rotate: true
